Cinema/Areas/Admin/Controllers/HomeController.cs
using Cinema.Services.Bookings;
using Cinema.Services.Films;
using Cinema.Services.Shows;
using Cinema.Services.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class HomeController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly IShowService _showService;
        private readonly IUserService _userService;
        private readonly IBookingService _bookingService;

        public HomeController(IFilmService filmService,
            IShowService showService,
            IUserService userService,
            IBookingService bookingService)
        {
            _filmService = filmService;
            _showService = showService;
            _userService = userService;
            _bookingService = bookingService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                // Attempt to retrieve data including films, shows, total users, and total booking revenues asynchronously
                var films = await _filmService.GetFilms();
                var shows = await _showService.GetShows();
                var users = await _userService.GetTotalUsers();
                var revenues = await _bookingService.GetTotalBooking();

                // Set ViewData with the obtained data
                ViewData["totalMovie"] = films.Count;
                ViewData["totalUser"] = users;
                ViewData["totalShow"] = shows.Count;
                ViewData["totalRevenue"] = revenues;
            }
            catch (Exception ex)
            {
                // If an exception occurs while retrieving data, it is caught here
                // Error handling could be implemented if needed
            }

            // Return the view
            return View();

        }
    }
}

Cinema/Areas/User/Controllers/HomeController.cs
using Cinema.Models;
using Cinema.Services.Films;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cinema.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFilmService _filmService;

        public HomeController(ILogger<HomeController> logger, IFilmService filmService)
        {
            _logger = logger;
            _filmService = filmService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var films = await _filmService.GetFilms();

                return View(films);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cinema/Controllers/FilmController.cs
using Cinema.Models;
using Cinema.Services.Films;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmService _filmService;

        public FilmController(IFilmService filmService)
        {
            _filmService = filmService;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int filmId)
        {
            Film film = await _filmService.GetFilmById(filmId);
            return View(film);
        }
    }
}

Cinema/Controllers/HomeController.cs
using Cinema.Models;
using Cinema.Services.Films;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cinema.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFilmService _filmService;

        public HomeController(ILogger<HomeController> logger, IFilmService filmService)
        {
            _logger = logger;
            _filmService = filmService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var films = await _filmService.GetFilms();

                return View(films);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cinema/Controllers/MenuController.cs
using Cinema.Requests;
using Cinema.Services.Films;
using Cinema.Services.Genres;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class MenuController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly IGenreService _genreService;

        public MenuController(IFilmService filmService, IGenreService genreService)
        {
            _filmService = filmService;
            _genreService = genreService;
        }

        public async Task<IActionResult> Index(FilmPagingRequest request)
        {
            try
            {
                ViewData["Genres"] = await _genreService.GetAll();

                var response = await _filmService.GetFilmByCondition(request);
                return View(response);
            }
            catch (Exception ex)
            {
            }
            return View();
        }
    }
}

Cinema/Areas/User/Views/Home/Index.cshtml
@using Cinema.Models;
@model List<Film>

<div class="hero_area mb-3">
    <div class="bg-box">
        <img src="~/assets/images/cinema.jpg" alt="">
    </div>
    <section class="slider_section ">
        <div id="customCarousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="container ">
                        <div class="row">
                            <div class="col-md-7 col-lg-6 ">
                                <div class="detail-box">
                                    <h1>
                                        Cinema ticket
                                    </h1>
                                    <p>
                                        Experience the highest quality cinema at Cinema cinemas nationwide. The information page
                                        summarizes the latest movie showtimes and trailers at Cinema Cinemas Vietnam.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item ">
                    <div class="container ">
                        <div class="row">
                            <div class="col-md-7 col-lg-6 ">
                                <div class="detail-box">
                                    <h1>
                                        Special offer for new subscribers.
                                    </h1>
                                    <p>
                                        Doloremque, itaque aperiam facilis rerum, commodi, temporibus sapiente ad mollitia laborum quam
                                        quisquam esse error unde. Tempora ex doloremque, labore, sunt repellat dolore, iste magni quos
                                        nihil ducimus libero ipsam.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container ">
                        <div class="row">
                            <div class="col-md-7 col-lg-6 ">
                                <div class="detail-box">
                                    <h1>
                                        Weekly promotion.
                                    </h1>
                                    <p>
                                        Doloremque, itaque aperiam facilis rerum, commodi, temporibus sapiente ad mollitia laborum quam
                                        quisquam esse error unde. Tempora ex doloremque, labore, sunt repellat dolore, iste magni quos
                                        nihil ducimus libero ipsam.
                                    </p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <ol class="carousel-indicators">
                    <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
                    <li data-target="#customCarousel1" data-slide-to="1"></li>
                    <li data-target="#customCarousel1" data-slide-to="2"></li>
                </ol>
            </div>
        </div>

    </section>
    <!-- end slider section -->
</div>
<!-- end offer section -->
<!--Viewer-->
<section class="food_section layout_padding-bottom">
    <div class="container">
        <div class="heading_container heading_center">
            <h2>New Movie</h2>
        </div>

        <!-- List Products -->
        <div class="filters-content">
            <div class="row grid">

                @foreach (var item in Model)
                {
                    <div class="col-sm-6 col-lg-4 all pizza">
                        <div class="box">
                            <div>
                                <div class="img-box">
                                    <img src=@item.Img alt="">
                                </div>
                                <div class="detail-box">
                                    <h5>
                                        @item.Title
                                    </h5>
                                    <p>
                                        @item.Description
                                    </p>
                                    <div class="options">
                                        <h6>
                                            Time: @item.Time minute
                                        </h6>
                                        <a asp-area="" asp-controller="Film" asp-action="Details" asp-route-filmId="@item.FilmId" class="" style="color: black; text-decoration: none">
                                            <i class="icon fa fa-solid fa-eye"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="btn-box">
            <a asp-controller="Menu" asp-action="Index">
                View More
            </a>
        </div>
    </div>
</section>