Cinema/Models/Seat.cs
using System;
using System.Collections.Generic;

namespace Cinema.Models
{
    public partial class Seat
    {
        public Seat()
        {
            Bookings = new HashSet<Booking>();
        }

        public int SeatId { get; set; }
        public string SeatName { get; set; } = null!;

        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

Cinema/Areas/User/Controllers/SeatController.cs
using Cinema.Models;
using Cinema.Services.Bookings;
using Cinema.Services.Shows;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]

    public class SeatController : Controller
    {
        private readonly IShowService _showService;
        private readonly IBookingService _bookingService;

        public SeatController(IShowService showService, IBookingService bookingService)
        {
            _showService = showService;
            _bookingService = bookingService;
        }

        [HttpPost]
        public async Task<IActionResult> ChooseShowMovie(int filmId, DateTime date)
        {
            // Create a list to store the dates for the next 7 days starting from today
            List<DateTime> dates = new();
            for (int i = 0; i < 7; i++)
            {
                dates.Add(DateTime.Now.AddDays(i));
            }

            // Retrieve shows for the specified film and date asynchronously
            List<Show> shows = await _showService.GetShowByFilmAndDate(filmId, date);

            // Set ViewData with film ID and dates list
            ViewData["filmId"] = filmId;
            ViewData["dates"] = dates;

            // Return the view with the shows for display
            return View(shows);

        }

        [HttpGet]
        public async Task<IActionResult> ChooseSeatShow(int showId)
        {
            // Retrieve show details by its ID asynchronously
            Show show = await _showService.GetShowById(showId);

            // Set ViewData with the retrieved show details
            ViewData["Show"] = show;

            // Retrieve booked seats for the specified show asynchronously
            List<Seat> seats = await _bookingService.GetSeatsIsBooked(showId);

            // Return the view with the booked seats for display
            return View(seats);

        }

        [HttpGet]
        public async Task<IActionResult> ChooseShowMovie(int filmId)
        {
            // Calculate the date 7 days from today
            DateTime next7Days = DateTime.Now.AddDays(7);

            // Create a list to store the dates for the next 7 days starting from today
            List<DateTime> dates = new();
            for (int i = 0; i < 7; i++)
            {
                dates.Add(DateTime.Now.AddDays(i));
            }

            // Retrieve shows for the specified film and date asynchronously
            List<Show> shows = await _showService.GetShowByFilmAndDate(filmId, next7Days);

            // Set ViewData with film ID and dates list
            ViewData["filmId"] = filmId;
            ViewData["dates"] = dates;

            // Return the view with the shows for display
            return View(shows);

        }
    }
}

Cinema/Areas/User/Views/Seat/ChooseSeatShow.cshtml
@using Cinema.Models
@model List<Seat>
@{
    int size = Model.Count;
    Show? show = ViewData["Show"] as Show;

    int i = 1;
    int index = 0;

}

<style>

    .movie-container {
        margin: 20px 0;
        background-color: #242333;
        color: #fff;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        font-family: "Lato", sans-serif;
        margin: 0;
    }

        .movie-container select {
            background-color: #fff;
            border: 0;
            border-radius: 5px;
            font-size: 16px;
            margin-left: 10px;
            padding: 5px 15px 5px 15px;
            -moz-appearance: none;
            -webkit-appearance: none;
            appearance: none;
        }

    .container {
        perspective: 1000px;
        margin-bottom: 30px;
    }

    .showcase {
        display: flex;
        justify-content: space-between;
    }

    .status {
        margin-left: 10px;
        text-align: center;
        display: flex;
    }

    .seat .small {
        margin-top: 20px;
        font-size: 20px;
    }

    .seat {
        background-color: #444451;
        height: 26px;
        width: 32px;
        margin: 3px;
        font-size: 50px;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }

        .seat.selected {
            background-color: green;
        }

        .seat.sold {
            background-color: #fff;
        }

        .seat:not(.sold):hover {
            cursor: pointer;
            transform: scale(1.2);
        }

    .showcase .seat:not(.sold):hover {
        cursor: default;
        transform: scale(1);
    }


    .row {
        display: flex;
    }

    .screen {
        background-color: #fff;
        height: 120px;
        width: 100%;
        margin: 15px 0;
        transform: rotateX(-48deg);
        box-shadow: 0 3px 10px rgba(255, 255, 255, 0.7);
    }

    p.text {
        margin: 5px 0;
    }

        p.text span {
            color: rgb(158, 248, 158);
        }

</style>

<section class="about_section layout_padding">
    <div class="container  ">
        <div class="row">
            <div class="col-md-12 movie-container">
                <h4 class="text-center" style="margin-top: -150px; margin-bottom: 100px;">
                    Film: @show.Film.Title <br />
                    Slot: @show.Slot.Time <br />
                    Time: @show.Film.Time minutes.
                </h4>
                <div class="showcase">
                    <div class="status">
                        <div class="seat"></div>
                        <small>Available</small>
                    </div>
                    <div class="status">
                        <div class="seat sold"></div>
                        <small>Sold</small>
                    </div>
                    <div class="status">
                        <div class="seat selected"></div>
                        <small>Selected</small>
                    </div>
                </div>
                <div class="containers">
                    <div class="screen"></div>
                    @if (size == 0)
                    {   @for (int outside = 1; outside <= 6; outside++)
                        {
                            <div class="row">
                                @for (int inside = 1; inside <= 8; inside++)
                                {
                                    <div class="seat" onclick="choose(this)" id="@(i++)"></div>
                                }
                            </div>
                        }

                    }
                    else
                    {
                        @for (int outside = 1; outside <= 6; outside++)
                        {
                            <div class="row">
                                @for (int inside = 1; inside <= 8; inside++)
                                {
                                    @if (i == Model.ElementAt(index).SeatId)
                                    {
                                        <div class="seat sold" id="@(i++)"></div>

                                        @if (index < size - 1)
                                        {
                                            index++;
                                        }
                                    }
                                    else
                                    {
                                        <div class="seat" onclick="choose(this)" id="@(i++)"></div>
                                    }
                                }
                            </div>
                        }

                    }

                </div>

                <form asp-area="User" asp-controller="Booking" asp-action="BookSeats" method="post" id="formBooking">
                    <input type="hidden" id="seatStr" name="seatStr" />
                    <input type="hidden" value="@show.ShowId" name="showId">
                </form>
                <button class=" mt-5 btn btn-primary" type="button" onclick="submit()">
                    Submit
                </button>
            </div>
        </div>
    </div>
</section>

<script>
    const arr = [];

    function choose(a) {
        console.log(a.id);
        const f = arr.findIndex((e) => e == a.id);
        // console.log(f);
        if (f == -1) {
            document.getElementById(a.id).style.backgroundColor = "green";
            arr.push(a.id)
            // console.log(arr)
        } else {
            document.getElementById(a.id).style.backgroundColor = "#444451";
            arr.splice(f, f + 1);
            // console.log(arr);
        }
    }

    function submit() {
     let seatStr = "";
    for (var i = 0; i < arr.length; i++)
    {
        if (i != arr.length - 1)
        {
            seatStr += arr[i] + ",";
        }
        else
        {
            seatStr += arr[i];
        }
    }

        console.log("seatStr: " + seatStr);
        document.getElementById("seatStr").value = seatStr;
        var form = document.getElementById("formBooking");
        form.submit();
    }
</script>

Cinema/Areas/User/Views/Seat/ChooseShowMovie.cshtml
@using Cinema.Models
@model List<Show>

@{
    Show? first = Model.FirstOrDefault();
    List<DateTime>? dates = ViewData["dates"] as List<DateTime>;
    int filmId = 0;
    int.TryParse(ViewData["days"]?.ToString(), out filmId);
}

<section class="container mt-5">
    @if (Model.Count == 0)
    {
        <h1 >No movie slots of the day</h1>
    }
    else
    {
        <section class="bg-light">
            <div class=" pb-5">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="card  border-0">
                            <img class="card-img img-fluid"
                                 src="@first?.Film.Img"
                                 style="object-fit: cover; height: 500px;"
                                 alt="Card image cap" id="product-detail">
                        </div>
                    </div>
                    <!-- col end -->
                    <div class="col-lg-7 ">
                        <div class="card border-0" style="height: 500px">
                            <div class="card-body">
                                <h1 class="h2">Active Show</h1>
                                <h4 class="mt-3">Date: </h4>
                                <div class="d-flex flex-wrap">
                                    @foreach (var date in dates)
                                    {
                                        <a asp-area="User" asp-controller="Seat" asp-action="ChooseShowMovie" asp-route-filmId="@filmId" asp-route-date="@date" class="btn btn-success me-2 mb-2">
                                            @date.ToShortDateString()
                                        </a>
                                    }
                                </div>

                                <div class="mt-5">
                                    <h4>Slot: @first.ShowDate.ToShortDateString()</h4>
                                    <div>
                                        @foreach (var item in Model)
                                        {
                                            <a asp-area="User" asp-controller="Seat" asp-action="ChooseSeatShow" asp-route-showId="@item?.ShowId" class="btn btn-primary col-md-2">@item?.Slot.Time</a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }



</section>