Cinema/Models/Show.cs
using System;
using System.Collections.Generic;

namespace Cinema.Models
{
    public partial class Show
    {
        public Show()
        {
            Bookings = new HashSet<Booking>();
        }

        public int ShowId { get; set; }
        public DateTime ShowDate { get; set; }
        public int SlotId { get; set; }
        public int FilmId { get; set; }
        public int RoomId { get; set; }
        public int? Status { get; set; }

        public virtual Film Film { get; set; } = null!;
        public virtual Room Room { get; set; } = null!;
        public virtual Slot Slot { get; set; } = null!;
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

Cinema/Areas/Admin/Controllers/ShowController.cs
using Cinema.Services.Films;
using Microsoft.AspNetCore.Mvc;
using Cinema.Models;
using Cinema.Services.Shows;
using Cinema.Helpers;
using Cinema.Services.Rooms;
using Cinema.Services.Slots;
using Cinema.Requests;
using Microsoft.AspNetCore.Authorization;
namespace Cinema.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class ShowController : Controller
    {
        private readonly IShowService _showService;
        private readonly IRoomService _roomService;
        private readonly IFilmService _filmService;
        private readonly ISlotService _slotService;

        public ShowController(IShowService showService,
            IRoomService roomService,
            IFilmService filmService,
            ISlotService slotService)
        {
            _showService = showService;
            _roomService = roomService;
            _filmService = filmService;
            _slotService = slotService;
        }

        public async Task<IActionResult> Index(ShowPagingRequest request)
        {
            try
            {
                // Set the page size for pagination
                request.PageSize = 10;

                // Retrieve shows based on the provided request asynchronously
                var response = await _showService.GetShows(request);

                // Return the view with the shows response for display
                return View(response);
            }
            catch (Exception ex)
            {
                // If an exception occurs during the retrieval process, it is caught here
                // Error handling could be implemented if needed
            }

            // Return the view with the original request object
            return View(request);

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // Retrieve films, slots, and rooms asynchronously and set them in ViewData
            ViewData["Films"] = await _filmService.GetFilms();
            ViewData["Slots"] = await _slotService.GetSlots();
            ViewData["Rooms"] = await _roomService.GetRooms();

            // Return the view 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Show show)
        {
            try
            {
                // Retrieve films, slots, and rooms asynchronously and set them in ViewData
                ViewData["Films"] = await _filmService.GetFilms();
                ViewData["Slots"] = await _slotService.GetSlots();
                ViewData["Rooms"] = await _roomService.GetRooms();

                // Set the status of the show
                show.Status = 1;

                // Attempt to add the show asynchronously
                bool response = await _showService.AddShow(show);

                // Check if show creation was unsuccessful
                if (response == false)
                {
                    // If show creation failed, throw an exception with an error message
                    throw new Exception("Create show failed.");
                }

                // If show creation is successful, display a success message to the user
                ToastHelper.ShowSuccess(TempData, "Create show successful.");

                // Redirect the user to the index page
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // If an exception occurs during the show creation process, catch it here
                // Display an error message to the user
                ToastHelper.ShowError(TempData, ex.Message);
            }

            // Return the view with the show object for the user to retry show creation
            return View(show);

        }

        [HttpGet]
        public async Task<IActionResult> Details(int showId)
        {

            // Retrieve films, slots, and rooms asynchronously and set them in ViewData
            ViewData["Films"] = await _filmService.GetFilms();
            ViewData["Slots"] = await _slotService.GetSlots();
            ViewData["Rooms"] = await _roomService.GetRooms();

            // Retrieve show details by its ID asynchronously
            Show show = await _showService.GetShowById(showId);

            // Return the view with the show details for display
            return View(show);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int showId)
        {
            // Retrieve films, slots, and rooms asynchronously and set them in ViewData
            ViewData["Films"] = await _filmService.GetFilms();
            ViewData["Slots"] = await _slotService.GetSlots();
            ViewData["Rooms"] = await _roomService.GetRooms();

            // Retrieve show details by its ID asynchronously
            Show show = await _showService.GetShowById(showId);

            // Return the view with the show details for display
            return View(show);

        }

        [HttpPost]
        public async Task<IActionResult> Update(Show show)
        {
            try
            {
                // Retrieve films, slots, and rooms asynchronously and set them in ViewData
                ViewData["Films"] = await _filmService.GetFilms();
                ViewData["Slots"] = await _slotService.GetSlots();
                ViewData["Rooms"] = await _roomService.GetRooms();

                // Attempt to update the show asynchronously
                bool response = await _showService.UpdateShow(show);

                // Check if show update was unsuccessful
                if (response == false)
                {
                    // If show update failed, throw an exception with an error message
                    throw new Exception("Update show failed.");
                }

                // If show update is successful, display a success message to the user
                ToastHelper.ShowSuccess(TempData, "Update show successful.");

                // Redirect the user to the index page
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // If an exception occurs during the show update process, catch it here
                // Display an error message to the user
                ToastHelper.ShowError(TempData, ex.Message);
            }

            // Return the view with the show object for the user to retry show update
            return View(show);

        }
    }
}

Cinema/Areas/Admin/Views/Show/Create.cshtml
@using Cinema.Models
@model Show

@{
    var films = ViewData["Films"] as List<Film>;
    var slots = ViewData["Slots"] as List<Slot>;
    var rooms = ViewData["Rooms"] as List<Room>;
}
<div class="pagetitle">
    <h1>Add New Show</h1>
</div><!-- End Page Title -->

<div class="container rounded bg-white card border-0 p-3">
    <form asp-area="Admin" asp-controller="Show" asp-action="Create" method="post">
        <div class="row">
            <div class="col-md-12">
                <label class="mb-1">Choose film</label>
                <select asp-for="FilmId" class="form-control">
                    @if (films != null)
                    {
                        @foreach (var item in films)
                        {
                            <option value="@item.FilmId">@item.Title</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose date</label>
                <input asp-for="ShowDate" type="date" required class="form-control"
                       placeholder="premiere" value="">
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose slot</label>
                <select asp-for="SlotId" class="form-control">
                    @if (slots != null)
                    {
                        @foreach (var item in slots)
                        {
                            <option value="@item.SlotId">@item.Time</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose theater</label>
                <select asp-for="RoomId" class="form-control">
                    @if (rooms != null)
                    {
                        @foreach (var item in rooms)
                        {
                            <option value="@item.RoomId">@item.Name</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="mt-3">
            <button class="btn btn-primary  w-100" type="submit">Save</button>
        </div>
    </form>
</div>

Cinema/Areas/Admin/Views/Show/Details.cshtml
@using Cinema.Models
@model Show

@{
    var films = ViewData["Films"] as List<Film>;
    var slots = ViewData["Slots"] as List<Slot>;
    var rooms = ViewData["Rooms"] as List<Room>;
}
<div class="pagetitle">
    <h1>Show Details</h1>
</div><!-- End Page Title -->

<div class="container rounded bg-white card border-0 p-3">
    <div class="row">
        <div class="col-md-12">
            <label class="mb-1">Film</label>
            <select disabled asp-for="FilmId" class="form-control">
                @if (films != null)
                {
                    @foreach (var item in films)
                    {
                        <option value="@item.FilmId">@item.Title</option>
                    }
                }
            </select>
        </div>
        <div class="col-md-12 mt-3">
            <label class="mb-1">Date</label>
            <input value="@Model.ShowDate.ToString("yyyy-MM-dd")" type="date" disabled class="form-control"
                   placeholder="premiere" value="">
        </div>
        <div class="col-md-12 mt-3">
            <label class="mb-1">Slot</label>
            <select disabled asp-for="SlotId" class="form-control">
                @if (slots != null)
                {
                    @foreach (var item in slots)
                    {
                        <option value="@item.SlotId">@item.Time</option>
                    }
                }
            </select>
        </div>
        <div class="col-md-12 mt-3">
            <label class="mb-1">Theater</label>
            <select disabled asp-for="RoomId" class="form-control">
                @if (rooms != null)
                {
                    @foreach (var item in rooms)
                    {
                        <option value="@item.RoomId">@item.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="mt-3">
        <a class="btn btn-primary  w-100" asp-area="Admin" asp-controller="Show" asp-action="Update" asp-route-showId="@Model.ShowId">Save</a>
    </div>
</div>

Cinema/Areas/Admin/Views/Show/Index.cshtml
@using Cinema.Requests
@using Cinema.Models
@model ShowPagingRequest
@{
    int totalRecord = (int)Model.TotalRecord;
    int totalPages = (int)Model.TotalPages;
    int currentPage = Model.CurrentPage;
    int pageSize = Model.PageSize;

    int startPage = Math.Max(1, currentPage - 2);
    int endPage = Math.Min(totalPages, currentPage + 2);

    int startIndex = ((currentPage - 1) * pageSize) + 1;
    int endIndex = startIndex + pageSize - 1;
    if (endIndex > totalRecord) endIndex = totalRecord;

    int ordinalNumber = 1;
}

<div class="pagetitle">
    <h1>List Show</h1>
</div><!-- End Page Title -->

<div class="card h-100 border-0 p-3">

    <div class="row mb-2">
        <form id="form-search" method="get" asp-area="Admin" asp-controller="Show" asp-action="Index">
            <input name="IsSearch" type="hidden" value="true">
            <div class="row">
                <div class=" col-sm-12 col-lg-8 pe-lg-0">
                    <div class="input-group">
                        <input asp-for="@Model.SearchTerm" name="SearchTerm" type="text" class="form-control rounded-0 rounded-start"
                               id="search-term"
                               placeholder="Enter item name">
                        <button type="submit" class="btn btn-info rounded-0 rounded-end text-white">
                            <span><i class="bi bi-search"></i> Search</span>
                        </button>
                    </div>
                </div>
                <div class="col-sm-12 col-lg-4 pt-2 pt-lg-0 text-lg-end">
                    <a asp-area="Admin" asp-controller="Show" asp-action="Create" class="btn btn-primary">
                        <span><i class="bi bi-plus-circle-fill me-1"></i>Add new show</span>
                    </a>
                </div>
            </div>
            <input id="current-page" type="hidden" asp-for="CurrentPage" name="CurrentPage" />
        </form>
    </div>
    @if (Model?.Items?.Count > 0)
    {
        <div class="table-container">
            <table class="useful-table">
                <thead>
                    <tr>
                        <th>Index</th>
                        <th scope="col">Show Title</th>
                        <th scope="col">Theater</th>
                        <th scope="col">Date</th>
                        <th scope="col">Slot</th>
                    </tr>
                </thead>
                <tbody class="useful-table-body">
                    @foreach (Show item in Model.Items)
                    {
                        <tr>
                            <td>@(ordinalNumber++)</td>
                            <td>
                                <a class="link-underline" asp-area="Admin" asp-controller="Show" asp-action="Details" asp-route-showId="@item.ShowId">
                                    <span>@item.Film.Title</span>
                                </a>
                            </td>
                            <td>@item?.Room?.Name</td>
                            <td>@item?.ShowDate.ToShortDateString()</td>
                            <td>@item?.Slot?.Time</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div class="row d-flex justify-content-center align-content-center mt-3">
            <div class="col">
                <span class="fst-italic ">Show <strong>@startIndex - @endIndex</strong> in total of <strong> @totalRecord</strong> shows </span>
            </div>
            @if (totalPages > 1)
            {
                <ul class="pagination justify-content-end col">
                    <li class="page-item @((currentPage == 1) ? "disabled" : "")">
                        <a class="page-link link-paging" href="?currentPage=@(currentPage-1)" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>

                    @if (currentPage > 3)
                    {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                    }

                    @for (int pageIndex = startPage; pageIndex <= endPage; pageIndex++)
                    {
                        <li class="page-item @(pageIndex == currentPage ? "link-active" : "")">
                            <a class="page-link link-paging " href="?currentPage=@pageIndex">@pageIndex</a>
                        </li>
                    }

                    @if (currentPage < Math.Ceiling(totalRecord / 10.0) - 2)
                    {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                    }

                    <li class="page-item @((currentPage == totalPages) ? "disabled" : "")">
                        <a class="page-link link-paging" href="?currentPage=@(currentPage+1)">Next</a>
                    </li>
                </ul>

            }
        </div>
    }
    else
    {
        <div class="h-100">
            <h6 class="fw-bold">Shows not found.</h6>
        </div>
    }

</div>

Cinema/Areas/Admin/Views/Show/Update.cshtml
@using Cinema.Models
@model Show

@{
    var films = ViewData["Films"] as List<Film>;
    var slots = ViewData["Slots"] as List<Slot>;
    var rooms = ViewData["Rooms"] as List<Room>;
}
<div class="pagetitle">
    <h1>Update Show</h1>
</div><!-- End Page Title -->

<div class="container rounded bg-white card border-0 p-3">
    <form asp-area="Admin" asp-controller="Show" asp-action="Update" method="post">
        <input type="hidden" asp-for="ShowId" />
        <div class="row">
            <div class="col-md-12">
                <label class="mb-1">Choose film</label>
                <select asp-for="FilmId" class="form-control">
                    @if (films != null)
                    {
                        @foreach (var item in films)
                        {
                            <option value="@item.FilmId">@item.Title</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose date</label>
                <input name="ShowDate" value="@Model.ShowDate.ToString("yyyy-MM-dd")" type="date" required class="form-control"
                       placeholder="premiere" value="">
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose slot</label>
                <select asp-for="SlotId" class="form-control">
                    @if (slots != null)
                    {
                        @foreach (var item in slots)
                        {
                            <option value="@item.SlotId">@item.Time</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-12 mt-3">
                <label class="mb-1">Choose theater</label>
                <select asp-for="RoomId" class="form-control">
                    @if (rooms != null)
                    {
                        @foreach (var item in rooms)
                        {
                            <option value="@item.RoomId">@item.Name</option>
                        }
                    }
                </select>
            </div>
        </div>
        <div class="mt-3">
            <button class="btn btn-primary w-100" type="submit">Save</button>
        </div>
    </form>
</div>