Cinema/Controllers/AuthenController.cs
using Cinema.Enums;
using Cinema.Helpers;
using Cinema.Models;
using Cinema.Requests;
using Cinema.Services.Authens;
using Cinema.Services.Films;
using Cinema.Services.Genres;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Cinema.Controllers
{
    public class AuthenController : Controller
    {
        private readonly IAuthenService _authenService;

        public AuthenController(IAuthenService authenService)
        {
            _authenService = authenService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequest request)
        {

            try
            {
                // Attempt to login the user asynchronously
                User user = await _authenService.Login(request);

                // Check if the user authentication failed
                if (user == null)
                {
                    // If authentication failed, throw an exception with a specific error message
                    throw new Exception("Email or password isn't correct");
                }

                // Create claims for the authenticated user
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Email),
                        new Claim(ClaimTypes.Role, "User")
                    };

                // Create a claims identity using the claims and default authentication scheme
                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Create a UserInfo object containing details about the authenticated user
                UserInfo userInfo = new UserInfo()
                {
                    UserId = user.UserId,
                    Fullname = user.Fullname ?? "",
                    Email = user.Email,
                    Role = user.Role ?? (int)Role.User
                };

                // Sign in the user asynchronously
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity));

                // Store user information in the session
                SessionHelper.SetObject<UserInfo>(HttpContext.Session, "UserInfo", userInfo);

                // Redirect the user based on their role
                if (user.Role == (int)Role.User)
                {
                    // If the user is a regular user, redirect them to the User area's Index action
                    return RedirectToAction("Index", "Home", new { area = "User" });
                }
                else
                {
                    // If the user is an admin, redirect them to the Admin area's Index action
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
            }
            catch (Exception ex)
            {
                // If an exception occurs during the authentication process, catch it here
                // Display an error message to the user
                ToastHelper.ShowError(TempData, ex.Message);

                // Return the login view with the original login request object for the user to retry
                return View(request);
            }

        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequest request)
        {

            try
            {
                // Check if the confirmed password matches the entered password
                if (request.ConfirmPassword != request.Password)
                {
                    // If passwords do not match, throw an exception with an error message
                    throw new Exception("Password not match");
                }

                // Create a new User object with details from the registration request
                User user = new User()
                {
                    Fullname = request.Fullname,
                    Email = request.Email,
                    Password = request.Password,
                    Address = request.Address,
                    Phone = request.Phone,
                    Dob = request.Dob,
                    Gender = request.Gender,
                };

                // Attempt to register the user asynchronously
                bool status = await _authenService.Register(user);

                // Check if registration was unsuccessful
                if (!status)
                {
                    // If registration failed, throw an exception with an error message
                    throw new Exception("Register failed");
                }

                // If registration is successful, redirect the user to the login page
                return RedirectToAction(nameof(Login));
            }
            catch (Exception ex)
            {
                // If an exception occurs during the registration process, catch it here
                // Display an error message to the user
                ToastHelper.ShowError(TempData, ex.Message);

                // Return the registration view with the original registration request object for the user to retry
                return View(request);
            }

        }

        [HttpGet]
        [Route("/SignOut")]
        public async Task<IActionResult> LogOut()
        {
            try
            {
                // Remove user information and access token from the session
                SessionHelper.Remove(HttpContext.Session, "UserInfo");
                SessionHelper.Remove(HttpContext.Session, "AccessToken");

                // Sign out the user asynchronously
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch (Exception ex)
            {
                // If an exception occurs during sign out, catch it here
                // Display an error message to the user
                ToastHelper.ShowError(TempData, ex.Message);
            }

            // Redirect the user to the home page
            return RedirectToAction("Index", "Home");

        }
    }
}

Cinema/Controllers/FilmController.cs
using Cinema.Models;
using Cinema.Services.Films;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmService _filmService;

        public FilmController(IFilmService filmService)
        {
            _filmService = filmService;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int filmId)
        {
            Film film = await _filmService.GetFilmById(filmId);
            return View(film);
        }
    }
}

Cinema/Views/Shared/Layouts/_AdminLayout.cshtml
@{
    // UserInfo userInfo = SessionHelper.GetObject<UserInfo>(Context.Session, "UserInfo");

    var currentController = ViewContext.RouteData.Values["controller"] as string;
    var currentAction = ViewContext.RouteData.Values["action"] as string;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="shortcut icon" href="images/161-1616544_popcorn-icon-cinema-flat-icon-png.png" type="">
    <link rel="stylesheet" href="~/css/toast.css" asp-append-version="true" />

    <title> Cinema Ticket </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- nice select  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"
          integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ=="
          crossorigin="anonymous" />
    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/variables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <header id="header" class="header fixed-top">
        <div class="container-fluid d-flex align-items-center justify-content-between">

            <div>
                <a asp-controller="Home" asp-action="Index" class="logo scrollto me-auto me-lg-0">
                    <img src="/assets/images/logo.png" />
                </a>
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li class="nav-item " title="Sự kiện">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link @(currentController.Contains("Home") ? "active" : "")">
                           Home
                        </a>
                    </li><!-- End Events Nav -->

                    <li class="nav-item " title="Sự kiện">
                        <a asp-area="Admin" asp-controller="Film" asp-action="Index" class="nav-link @(currentController.Contains("Film") ? "active" : "")">
                           Film
                        </a>
                    </li><!-- End Events Nav -->

                    <li class="nav-item " title="Tin tức">
                        <a asp-area="Admin" asp-controller="Show" asp-action="Index" class="nav-link @(currentController.Contains("Show")  ? "active" : "")">
                            Show
                        </a>
                    </li><!-- End Events Nav -->

                </ul>

            </nav><!-- navbar -->


            <div>
                <a class="btn btn-primary" href="/SignOut">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Sign Out</span>
                </a>
            </div>

        </div>
        <div class="navbar-mobile" style="display: contents;">
            <a class="mobile-nav-toggle d-none" href="#" data-bs-toggle="dropdown">
                <i class="bi bi-list "></i>
            </a><!-- End Profile Iamge Icon -->
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow ">
                <li class="nav-item " title="Sự kiện">
                    <a asp-area="Admin" asp-controller="User" asp-action="Index" class="nav-link @(currentController.Contains("Home") ? "active" : "")">
                        Home
                    </a>
                </li><!-- End Events Nav -->

                <li class="nav-item " title="Sự kiện">
                    <a asp-area="Admin" asp-controller="District" asp-action="Index" class="nav-link @(currentController.Contains("Film") ? "active" : "")">
                        Film
                    </a>
                </li><!-- End Events Nav -->

                <li class="nav-item " title="Tin tức">
                    <a asp-area="Admin" asp-controller="Seri" asp-action="Index" class="nav-link @(currentController.Contains("Show")  ? "active" : "")">
                        Show
                    </a>
                </li><!-- End Events Nav -->
            </ul><!-- End Profile Dropdown Items -->

        </div>
    </header><!-- End Header -->


    <div class="container min-vh-100 pt-5">
        <main role="main" class="pt-4">
            @RenderBody()
        </main>
    </div>

    <footer class="py-4 bg-light">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Your Website 2022</div>
                <div>
                    <a href="#">Privacy Policy</a>
                    &middot;
                    <a href="#">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- isotope js -->
    <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        $(function () {

            var toastMessage = '@TempData["ToastMessage"]';
            var toastType = '@TempData["ToastType"]';
            if (toastMessage && toastType) {
                toastr[toastType](toastMessage);
            }
        });
    </script>
</body>
</html>

Cinema/Views/Shared/Layouts/_Layout.cshtml
@{
    var currentController = ViewContext.RouteData.Values["controller"] as string;
    var currentAction = ViewContext.RouteData.Values["action"] as string;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="shortcut icon" href="images/161-1616544_popcorn-icon-cinema-flat-icon-png.png" type="">
    <link rel="stylesheet" href="~/css/toast.css" asp-append-version="true" />

    <title> Cinema Ticket </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- nice select  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"
          integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ=="
          crossorigin="anonymous" />
    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>

    <header class="header_section">
        <div class="container">
            <nav class="navbar navbar-expand custom_nav-container ">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <span>
                        Cinema
                    </span>
                </a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav  mx-auto ">
                        <li class="nav-item @(currentController.Contains("Home") ? "active" : "")">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home </a>
                        </li>
                        <li class="nav-item @(currentController.Contains("Menu") ? "active" : "")">
                            <a class="nav-link " asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                    <div class="user_option">
                        <a asp-area="" asp-controller="Authen" asp-action="Login" class="order_online">
                            Login
                        </a>
                        <a asp-area="" asp-controller="Authen" asp-action="Register" class="order_online">
                            Register
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </header>


   
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer_section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 footer-col">
                    <div class="footer_contact">
                        <h4>
                            Contact Us
                        </h4>
                        <div class="contact_link_box">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span>
                                    Location
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span>
                                    Call +01 1234567890
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span>
                                    demo@gmail.com
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <div class="footer_detail">
                        <a href="" class="footer-logo">
                            Cinema
                        </a>
                        <p>
                            Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
                        </p>
                        <div class="footer_social">
                            <a href="#">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-pinterest" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 footer-col">
                    <h4>
                        Opening Hours
                    </h4>
                    <p>
                        Everyday
                    </p>
                    <p>
                        08.00 Am -11.59 Pm
                    </p>
                </div>
            </div>
            <div class="footer-info">
                <p>
                    &copy; <span id="displayYear"></span> All Rights Reserved By
                    <a href="https://html.design/">Cinema</a><br><br>
                </p>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- isotope js -->
    <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        $(function () {

            var toastMessage = '@TempData["ToastMessage"]';
            var toastType = '@TempData["ToastType"]';
            if (toastMessage && toastType) {
                toastr[toastType](toastMessage);
            }
        });
    </script>
</body>
</html>